int32 action

int32 ACTION_FIRST_MEASUREMENT_BEFORE_OBJECT_IS_GRASPED = 1
int32 ACTION_SECOND_MEASUREMENT_BEFORE_OBJECT_IS_GRASPED = 2
int32 ACTION_FIRST_MEASUREMENT_AFTER_OBJECT_IS_GRASPED = 3
int32 ACTION_SECOND_MEASUREMENT_AFTER_OBJECT_IS_GRASPED = 4
---
int32 error_code

int32 SUCCESSFUL = 0
int32 ERROR = -1
---

